name: Frontend CI + Playwright

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start backend
        run: |
          npm start &
          sleep 5 
        working-directory: ./backend

      - name: Start Vite server
        run: npm run dev &
        env:
          CI: true

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run Playwright tests
        run: npx playwright test

      # (опційно) Збереження скріншотів
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/



      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

