name: Frontend CI + Playwright

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Встановлюємо залежності для client
      - name: Install client dependencies
        run: npm ci
        working-directory: client

      # Встановлюємо залежності для backend
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      # Встановлення браузерів Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: client

      # Запускаємо backend
      - name: Start backend
        run: npm start &
        working-directory: backend

      # Чекаємо, поки backend буде готовий
      - name: Wait for backend to be ready
        run: npx wait-on http://localhost:3001

      # Запускаємо frontend (Vite)
      - name: Start frontend (Vite)
        run: npm run dev &
        working-directory: client
        env:
          CI: true

      # Чекаємо, поки фронт буде готовий
      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5173

      # Запускаємо Playwright тести
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: client

      # Артефакти зі скріншотами
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: client/test-results/

      # Деплой (якщо потрібно)
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
